apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jnlp-slave
  name: jnlp-slave
spec:
  serviceAccount: jenkins-agent
  volumes:
  - name: docker-socket
    emptyDir: {}
  containers:
  - name: jnlp-docker
    image: docker:19.03-git
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  - name: docker-daemon
    image: docker:19.03-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run

