apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jnlp-slave
  name: jnlp-slave
spec:
  containers:
    - name: jnlp-container
      image: ninech/jnlp-slave-with-docker
      imagePullPolicy: IfNotPresent
      env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"

    - name: "dind"
      image: docker:19.03.9-dind
      imagePullPolicy: IfNotPresent
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      securityContext:
        privileged: true
      