apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jnlp-slave
  name: jnlp-slave
spec:
  volumes:
    - name: docker-path
      hostPath:
        path: /var/run/docker.sock
    - name: workspace-volume
      emptyDir: {}
  containers:
  - name: jnlp
    env:
    - name: CONTAINER_ENV_VAR
      value: jnlp