#!/bin/sh -e

cd $(dirname $0)/..

source ./auto/set-env-vars

password="$( \
    docker run --rm \
        -e AWS_DEFAULT_REGION=${AWS_REGION} \
        amazon/aws-cli ecr get-login-password
)"

docker login \
    --password $password \
    --username AWS \
    "${ECR_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
