#! /bin/bash -e

cd $(dirname $0)/..

source ./auto/set-env-vars

if [[ $# -lt 2 ]]; then
	echo "No enough args!"
	echo "Usage: $0 AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY"
	echo "  AWS_ACCESS_KEY_ID: AWS accessKeyId"
	echo "  AWS_SECRET_ACCESS_KEY: AWS secretAccessKey"
	exit 1
fi

password="$( \
    docker run --rm -ti \
        --network=host \
        -e AWS_ACCESS_KEY_ID=$1 \
        -e AWS_SECRET_ACCESS_KEY=$2 \
        -e AWS_DEFAULT_REGION=${AWS_REGION} \
        amazon/aws-cli ecr get-login-password
)"

docker login \
    --password $password \
    --username AWS \
    "${ECR_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
