#!/bin/sh -e

AWS_REGION=${AWS_REGION:-ap-northeast-1}
ECR_ID="729601114034"

DOCKER_IMAGE="${ECR_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/official-website"
BN=${BUILD_NUMBER:-0}
TAG="${GITHASH}.${BN}"
IMAGE_TAR="image.tar"

GITHUB_OPS_IMAGE="${ECR_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/github-ops"
